### ISSUE TITLE
Inter-service communication

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#12]
### User Story

As a developer, I want my services to be able to exchange data so that my application can function properly.

### Description

Create a service bus that makes it possible to send and receive messages between different services.

### Acceptance Criteria

- [x] Acceptance criteria 1: 
```
Given that I have two services, Service A and Service B
When Service A emits an event that Service B has consumed
Then data should be sent to Service B
And the data exchange should be successful
```
- [ ] Acceptance criteria 2: 
```
Given Service A has data to send to Service B
But the "DataExchangeTopic" is currently unavailable
When Service A attempts to send a message
Then Service A should generate an error log
```

### Definition of Done

- [ ] Code is written or updated.
- [ ] Code compiles without errors.
- [ ] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [ ] Non-Functional requirements met.

### Tasks

- [ ] Task 1: Create service bus.
- [ ] Task 2: Create generic wrapper for publishing and subscribing to topics.
- [ ] Task 3: Implement service bus logic in microservices.
- [ ] Task 4: Test service bus.
