### ISSUE TITLE
Automated Gherkin Testing

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#13]
### User Story

As a developer, I want to write Gherkin tests and automatically run them in the pipeline, so that I can easily verify behaviour according to my user stories.

### Description

Run automated behavioral tests with SpecFlow

### Acceptance Criteria

- [x] Acceptance criteria 1:
```
Given Specflow is implemented in the CI/CD pipeline
When new code is pushed to the remote
Then the CI/CD pipeline should run all gherkin tests using SpecFlow
(And, But)
```

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] Task 1: Implement SpecFlow into CI/CD pipeline.
- [x] Task 2: Write Gherkin tests.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
