### ISSUE TITLE
CI/CD pipelines

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#15]
### User Story

As a Software developer, I want a CI/CD so that I can automate the building, testing and deployment of my application.

### Description

Set up CI/CD pipelines for the project.

### Acceptance Criteria

- [x] Acceptance criteria 1:
```
Given the CI pipeline has successfully built and tested the code
And there is an open merge request
When all tests pass and the build is successful
Then a merge of the new code into the production branch should be allowed
```
- [x] Acceptance criteria 2: 
```
Given the CI pipeline has successfully built and tested the code
When all tests pass and the build is successful
Then the CD pipeline should be triggered to deploy the application to the production environment
```

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [x] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] Task 1: Create pipeline for development environment 
- [x] Task 2: List another task if needed.
- [x] Task 3: List additional tasks as necessary.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
