### ISSUE TITLE
Role-based Access Control

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#16]
### User Story

As a system admin, I want to prevent users from accessing content they should not be allowed to so that I can protect my data and prevent unwanted changes from being made.

### Description

Add role-based access control.

### Acceptance Criteria

- [x] Acceptance criteria 1:
```
Given a user with 'standard' privileges attempts to access 'admin-only' content
When they try to view or edit this content
Then they should receive an 'Access Denied' message
And the attempt should be logged for audit purposes
```
- [x] Acceptance criteria 2: 
```
Given a user with 'admin' privileges attempts to access 'admin-only' content
When they try to view or edit this content
Then they should be able to access the content without any error messages
```

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [x] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] Task 1: List any specific tasks that need to be completed to implement this user story.
- [x] Task 2: List another task if needed.
- [x] Task 3: List additional tasks as necessary.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
