### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#17]
### User Story

As a user, I want to log into my account so that I can access my data and use the application.

### Description

Create login functionality for users.

### Acceptance Criteria

- [x] Acceptance criteria 1:
```
Given the user has the correct login information
When the user navigates to the login page
And the user enters the correct username and password
And the user clicks on the login button
Then the user should be directed to their dashboard
```
- [x] Acceptance criteria 2: 
```
Given the user has the wrong password
When the user navigates to the login page
And the user enters the correct username and an incorrect password
And the user clicks on the login button
Then the user should see an error message "Incorrect password. Please try again."
```
- [x] Acceptance criteria 3:
```
Given the user leaves the username and password fields blank
When the user navigates to the login page
And the user clicks on the login button
Then the user should see an error message "Please enter username and password."
```

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [x] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] Task 1: Implement Firebase Auth.
- [x] Task 2: Create middleware or link to account service.
- [x] Task 3: Create account page.
- [x] Task 4: Create login UI functionality.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
