### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#18]
### User Story

As a user, I want an account so that my relevant data can be stored and reused.

### Description

Create user registration functionality

### Acceptance Criteria

- [x] Acceptance criteria 1:
```
Given the user is a new visitor on the website
When the user navigates to the Sign-Up page
Then they should see a form to create a new account
```
- [x] Acceptance criteria 2: 
```
Given the user is on the Sign-Up page
When the user provides their personal information including full name, email address, and password
And submits the sign-up form
Then the user should receive a confirmation message that their account has been created
```
- [x] Acceptance criteria 3:
```
Given the user is on the Sign-Up page
And the email address they entered is already associated with an existing account
When the user attempts to submit the sign-up form
Then the user should see a message informing them that the email is already in use
And the user should be given the option to recover their password or use a different email to sign up
```
- [x] Acceptance criteria 4:
```
Given the user is on the Sign-Up page
When the user submits the sign-up form with invalid data
Then the user should be shown messages indicating the problems with the data entered
And the account should not be created until all the data is valid
```
- [x] Acceptance criteria 5:
```
Given the user's account has been successfully created
And they have confirmed their email address
When the user logs in with their email and password
Then they should be taken to the dashboard
```

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [x] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] Task 1: Implement firebase auth.
- [x] Task 2: List another task if needed.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
