### ISSUE TITLE
Message notifications

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#19]
### User Story

As a user, I want a message notification so that I know when someone has messaged me.

### Description

Receive a push notification the moment that I receive a new message from another user.

### Acceptance Criteria

- [ ] Acceptance criteria 1:
```
Given the user has not turned off their notifications
When the user receives a new message
Then a notification should appear indicating a new message has been received
And the notification should display the sender's name and a preview of the message
```
- [ ] Acceptance criteria 2: 
```
Given the user receives several messages in a short period of time
When these messages are from the same conversation
Then the user should receive a single notification summarizing the number of new messages
And the notification should display the most recent message preview
```
- [ ] Acceptance criteria 3:
```
Given the user has received a new message notification
When the user taps on the message notification
Then the application should open and navigate to the corresponding conversation thread
```

### Definition of Done

- [ ] Code is written or updated.
- [ ] Code compiles without errors.
- [ ] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [ ] Non-Functional requirements met.

### Tasks

- [ ] Task 1: Create notification service.
- [ ] Task 2: Link up to webpush API to send out push notifications.
- [ ] Task 3: Make use of PWA service worker to get native mobile notifications.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
