### ISSUE TITLE
Edit Market listings

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#21]
### User Story

As an airsoft technician, I want to be able to edit my listings so that I can make sure my listings have the most up-to-date information.

### Description

Make it possible to edit listings.

### Acceptance Criteria

- [ ] Acceptance criteria 1:
```
When I navigate to my existing listing
And I click on the "Edit" button for the listing
Then I should be able to edit the text in all editable fields including "title", "description", "price", and "photos"
When I update the "title", "description", "price", and change "photos"
And I click on the "Save" button
Then the listing should be updated with the new information
And the updated listing should be displayed to confirm the changes
```
- [ ] Acceptance criteria 2: 
```
When I navigate to my existing listing
And I click on the "Edit" button for the listing
Then I should be able to edit the text in all editable fields including "title", "description", "price", and "photos"
When I update only the "price" field
And I click on the "Save" button
Then the listing should be updated with the new price
And the updated listing should be displayed to confirm the change
```
- [ ] Acceptance criteria 3:
```
When I navigate to my existing listing
And I click on the "Edit" button for the listing
Then I should be taken to the listing editing page
When I make changes to the "title" and "description"
But I click on the "Cancel" button
Then the listing should not be updated
And the original listing information should be displayed
```

### Definition of Done

- [ ] Code is written or updated.
- [ ] Code compiles without errors.
- [ ] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [ ] Non-Functional requirements met.

### Tasks

- [ ] Task 1: Add functionality to edit listings

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
