### ISSUE TITLE
Group messaging

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#22]
### User Story

As a user, I want to be able to create group chats so that I can talk with multiple people in the same chat.

### Description

Be able to create GCs to communicate with multiple people in one chat.

### Acceptance Criteria

- [ ] Acceptance criteria 1:
```
When the user selects the option to create a new group chat
And the user specifies a group chat name
And the user adds at least one other participant by username or contact information
Then a new group chat should be created
And the user should be able to send messages to the group chat
And all participants should receive messages sent to the group chat
```
- [ ] Acceptance criteria 2: 
```
Given an existing group chat with participants
When the user adds another participant by username or contact information to the group chat
Then the newly added participant should receive an invitation to join the group chat
And upon acceptance, the new participant should be added to the group chat
And the new participant should be able to send and receive messages
```
- [ ] Acceptance criteria 3:
```
When the user attempts to create a group chat without adding any participants
Then the system should prompt the user to add at least 2 other participants
```
- [ ] Acceptance criteria 4:
```
When the user creates a group chat with a name that already exists in their chat list
Then the system should allow the group chat creation
And the system may append a number or symbol to distinguish the new group chat from existing ones
```
- [ ] Acceptance criteria 5:
```
Given the user is a member of an existing group chat
When the user chooses to leave the group chat
Then the user should be removed from the group chat
And the user should no longer receive messages from the group chat
```

### Definition of Done

- [ ] Code is written or updated.
- [ ] Code compiles without errors.
- [ ] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [ ] Non-Functional requirements met.

### Tasks

- [ ] Task 1: Create groupchat functionality.
- [ ] Task 2: Create relevant UI elements.

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
