### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#23]
### User Story

As a user, I want to be able to message other users so that I can communicate with them about airsoft related things.

### Description

Create messaging functionality.

### Acceptance Criteria

- [ ] Acceptance criteria 1:
```
When the user selects another user to message
And the user writes a message in the text input area
And the user clicks on the send button
Then the message should be sent to the selected user
And the user should see a confirmation that the message has been sent
```
- [ ] Acceptance criteria 2: 
```
Given another user has sent a message to the user
When the user is on the messaging page
Then the user should receive a notification of a new message
And the user should be able to view the new message
```
- [ ] Acceptance criteria 3:
```
Given the user has previous messages with another user
When the user selects the conversation with that user
Then the user should be able to see the message history with that user
```
- [ ] Acceptance criteria 4:
```
When the user attempts to send a message without any text
Then the send button should be greyed out
And when the user still clicks on the button they should be informed that a message cannot be empty
```

- [ ] Acceptance criteria 5:
```
When the user enters a keyword in the search bar
And the keyword corresponds to existing users' names or usernames
Then the user should see a list of users matching the keyword
And the user can select a user from the list to message
```

### Definition of Done

- [ ] Code is written or updated.
- [ ] Code compiles without errors.
- [ ] Security first considered for GDPR compliance.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated if necessary.
- [ ] User testing has been conducted and successful.
- [ ] Non-Functional requirements met.

### Tasks

- [ ] Task 1: Create messaging functionality.
- [ ] Task 2: Create relevant UI components

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]
