### ISSUE TITLE
Sprint 3 TODO list

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#27]
TODO:
- [x] CIA-based risk analysis.
- [x] Login & RBAC based on risk analysis.
- [x] Finish up outstanding user stories.
- [x] Automated testing framework implementation.
- [x] Expand portfolio with evidence.
