### ISSUE TITLE
Login & landing page

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/ICAP#8]
### User Story

As a user, I want to be able to log into the application so that I can access the application securely and view all the information relevant to me.

### Description

Create basic setup of the project with a login / landing page to start working from.

### Acceptance Criteria

- [x] [Acceptance criteria 1: User can log into application.]
- [x] [Acceptance criteria 2: User gets sent to a landing page when the url is entered, from which they can then log into the application.]

### Definition of Done

- [x] Code is written or updated.
- [x] Code compiles without errors.
- [x] Security first considered for GDPR compliance.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated if necessary.
- [x] User testing has been conducted and successful.
- [x] Non-Functional requirements met.

### Tasks

- [x] [Task 1: Create skeleton.]
- [x] [Task 2: Create landing page.]
- [x] [Task 3: Implement login functionality.]

### Related Issues/PRs

[Link to any related issues or pull requests if applicable]

### Additional Information

[Provide any additional context, information, or resources that may be helpful in completing this user story.]

### Epic

[Link to the epic or larger project that this user story is a part of, if applicable.]
